/*
Whisparr

Whisparr API docs

API version: 3.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package whisparr

import (
	"encoding/json"
)

// DiskSpaceResource struct for DiskSpaceResource
type DiskSpaceResource struct {
	Id *int32 `json:"id,omitempty"`
	Path NullableString `json:"path,omitempty"`
	Label NullableString `json:"label,omitempty"`
	FreeSpace *int64 `json:"freeSpace,omitempty"`
	TotalSpace *int64 `json:"totalSpace,omitempty"`
}

// NewDiskSpaceResource instantiates a new DiskSpaceResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDiskSpaceResource() *DiskSpaceResource {
	this := DiskSpaceResource{}
	return &this
}

// NewDiskSpaceResourceWithDefaults instantiates a new DiskSpaceResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDiskSpaceResourceWithDefaults() *DiskSpaceResource {
	this := DiskSpaceResource{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DiskSpaceResource) GetId() int32 {
	if o == nil || isNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiskSpaceResource) GetIdOk() (*int32, bool) {
	if o == nil || isNil(o.Id) {
    return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DiskSpaceResource) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *DiskSpaceResource) SetId(v int32) {
	o.Id = &v
}

// GetPath returns the Path field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DiskSpaceResource) GetPath() string {
	if o == nil || isNil(o.Path.Get()) {
		var ret string
		return ret
	}
	return *o.Path.Get()
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DiskSpaceResource) GetPathOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.Path.Get(), o.Path.IsSet()
}

// HasPath returns a boolean if a field has been set.
func (o *DiskSpaceResource) HasPath() bool {
	if o != nil && o.Path.IsSet() {
		return true
	}

	return false
}

// SetPath gets a reference to the given NullableString and assigns it to the Path field.
func (o *DiskSpaceResource) SetPath(v string) {
	o.Path.Set(&v)
}
// SetPathNil sets the value for Path to be an explicit nil
func (o *DiskSpaceResource) SetPathNil() {
	o.Path.Set(nil)
}

// UnsetPath ensures that no value is present for Path, not even an explicit nil
func (o *DiskSpaceResource) UnsetPath() {
	o.Path.Unset()
}

// GetLabel returns the Label field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DiskSpaceResource) GetLabel() string {
	if o == nil || isNil(o.Label.Get()) {
		var ret string
		return ret
	}
	return *o.Label.Get()
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DiskSpaceResource) GetLabelOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return o.Label.Get(), o.Label.IsSet()
}

// HasLabel returns a boolean if a field has been set.
func (o *DiskSpaceResource) HasLabel() bool {
	if o != nil && o.Label.IsSet() {
		return true
	}

	return false
}

// SetLabel gets a reference to the given NullableString and assigns it to the Label field.
func (o *DiskSpaceResource) SetLabel(v string) {
	o.Label.Set(&v)
}
// SetLabelNil sets the value for Label to be an explicit nil
func (o *DiskSpaceResource) SetLabelNil() {
	o.Label.Set(nil)
}

// UnsetLabel ensures that no value is present for Label, not even an explicit nil
func (o *DiskSpaceResource) UnsetLabel() {
	o.Label.Unset()
}

// GetFreeSpace returns the FreeSpace field value if set, zero value otherwise.
func (o *DiskSpaceResource) GetFreeSpace() int64 {
	if o == nil || isNil(o.FreeSpace) {
		var ret int64
		return ret
	}
	return *o.FreeSpace
}

// GetFreeSpaceOk returns a tuple with the FreeSpace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiskSpaceResource) GetFreeSpaceOk() (*int64, bool) {
	if o == nil || isNil(o.FreeSpace) {
    return nil, false
	}
	return o.FreeSpace, true
}

// HasFreeSpace returns a boolean if a field has been set.
func (o *DiskSpaceResource) HasFreeSpace() bool {
	if o != nil && !isNil(o.FreeSpace) {
		return true
	}

	return false
}

// SetFreeSpace gets a reference to the given int64 and assigns it to the FreeSpace field.
func (o *DiskSpaceResource) SetFreeSpace(v int64) {
	o.FreeSpace = &v
}

// GetTotalSpace returns the TotalSpace field value if set, zero value otherwise.
func (o *DiskSpaceResource) GetTotalSpace() int64 {
	if o == nil || isNil(o.TotalSpace) {
		var ret int64
		return ret
	}
	return *o.TotalSpace
}

// GetTotalSpaceOk returns a tuple with the TotalSpace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiskSpaceResource) GetTotalSpaceOk() (*int64, bool) {
	if o == nil || isNil(o.TotalSpace) {
    return nil, false
	}
	return o.TotalSpace, true
}

// HasTotalSpace returns a boolean if a field has been set.
func (o *DiskSpaceResource) HasTotalSpace() bool {
	if o != nil && !isNil(o.TotalSpace) {
		return true
	}

	return false
}

// SetTotalSpace gets a reference to the given int64 and assigns it to the TotalSpace field.
func (o *DiskSpaceResource) SetTotalSpace(v int64) {
	o.TotalSpace = &v
}

func (o DiskSpaceResource) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if o.Path.IsSet() {
		toSerialize["path"] = o.Path.Get()
	}
	if o.Label.IsSet() {
		toSerialize["label"] = o.Label.Get()
	}
	if !isNil(o.FreeSpace) {
		toSerialize["freeSpace"] = o.FreeSpace
	}
	if !isNil(o.TotalSpace) {
		toSerialize["totalSpace"] = o.TotalSpace
	}
	return json.Marshal(toSerialize)
}

type NullableDiskSpaceResource struct {
	value *DiskSpaceResource
	isSet bool
}

func (v NullableDiskSpaceResource) Get() *DiskSpaceResource {
	return v.value
}

func (v *NullableDiskSpaceResource) Set(val *DiskSpaceResource) {
	v.value = val
	v.isSet = true
}

func (v NullableDiskSpaceResource) IsSet() bool {
	return v.isSet
}

func (v *NullableDiskSpaceResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDiskSpaceResource(val *DiskSpaceResource) *NullableDiskSpaceResource {
	return &NullableDiskSpaceResource{value: val, isSet: true}
}

func (v NullableDiskSpaceResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDiskSpaceResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


